### PR TITLE
Update plugins to 2.0 API

### PR DESCRIPTION
**Pull request by samj1912**

### CODE REVIEW

**Comment by phw** [comment]
Why so many complete removals? Shouldn't we aim to update those, too?

**Comment by samj1912** [comment]
I am going to eventually port all of them. Currently these are the ones ported. I want them to be added so people can start using plugins ASAP.

The rest will be ported over this week. You are welcome to help :)

**Comment by mwiencek** [comment]
Shouldn't we just be able to make `PLUGIN_API_VERSIONS` an empty list instead of removing the files?

**Comment by samj1912** [comment]
@mwiencek the generation script will still pick it up and it will be displayed in Picard?

**Comment by mwiencek** [comment]
Is there a reason Picard displays incompatible plugins, or the generation script needs to pick them up? That was one of the problems I mentioned a while ago on IRC. Ideally I just think we shouldn't create these huge commits if we don't need to, since they inflate the size of the repo and make `git blame` harder to use.

**Comment by samj1912** [comment]
Fair point, Ill update the generation script to reject the plugins not within compatible apis.

**Comment by samj1912** [comment]
Updated this PR. Not deleting any files now, instead changed the generation script @ PW.

**Pull request merged**
